# Generated by Django 5.2.3 on 2025-06-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='section',
            new_name='recipe',
        ),
    ]
