# Generated by Django 5.2.1 on 2025-05-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='equipment',
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='recipes.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientSection',
        ),
    ]
